# src/utils/srt_to_ass.py
import subprocess
import os
import tempfile
import shutil
from typing import Optional


SAFE_ASS_HEADER = """[Script Info]
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,64,&H00FFFFFF,&H00FFFFFF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,3,0,2,60,60,120,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def srt_to_ass(srt_path: str) -> Optional[str]:
    """
    Converts SRT to ASS safely.
    Returns ASS path on success, None on failure.
    NEVER raises exception.
    """

    if not srt_path or not os.path.exists(srt_path):
        return None

    ass_path = srt_path.replace(".srt", ".ass")

    # Temporary ASS file generated by ffmpeg
    with tempfile.NamedTemporaryFile(
        delete=False, suffix=".ass"
    ) as tmp_ass:
        tmp_ass_path = tmp_ass.name

    try:
        # Step 1: Convert SRT -> ASS using ffmpeg
        cmd = [
            "ffmpeg", "-y",
            "-i", srt_path,
            tmp_ass_path
        ]

        subprocess.run(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=True
        )

        if not os.path.exists(tmp_ass_path):
            return None

        # Step 2: Extract dialogue lines only
        dialogue_lines = []
        with open(tmp_ass_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if line.startswith("Dialogue:"):
                    dialogue_lines.append(line.strip())

        if not dialogue_lines:
            return None

        # Step 3: Write safe ASS with controlled header
        with open(ass_path, "w", encoding="utf-8") as out:
            out.write(SAFE_ASS_HEADER + "\n")
            for line in dialogue_lines:
                out.write(line + "\n")

        if not os.path.exists(ass_path) or os.path.getsize(ass_path) == 0:
            return None

        return ass_path

    except Exception:
        return None

    finally:
        try:
            os.remove(tmp_ass_path)
        except OSError:
            pass
